name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USERNAME: ${{env.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{env.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t bkataru/impulses:sveltekit-node-ts .
    - name: Push the Docker image
      run: docker push bkataru/impulses:sveltekit-node-ts
